### ISSUE TITLE
Refreshing when signed in redirects user to home screen

### ISSUE THREAD

**Issue by QwertycowMoo** [Pan-Lang/panlang-ui#64]
This is because the useCollection hook for the database is using the user email to get the collection, but when you refresh, I think it erases the user and the useAuth hook isn't fast enough to send the page back to the main screen to get logged in again. Also since its a hook it gets run before the useEffect.
Is there a way to run the useCollection hook inside of the useEffect? I'm not too clear on how react hooks flow

Issue is not pushed to master, its only on branch 58-fire-realtime-order

**Comment by renzol2** [comment]
(Hijacking this issue since this new problem is a general version of the original lol)

## Problem
When loading or refreshing the page as a logged-in user, the page is rendered before the authentication is verified with Firebase, meaning that the user briefly sees the anonymous version before seeing their signed-in version. 

This also means that if a user is currently on a signed-in only screen (ex. order tracker, stock dash, etc.), they are automatically redirected to home screen, which can be a little annoying if you need to refresh the page for something.

## Fix
Render some loading screen as the authentication is verifying (useAuthState has a loading state), and prevent user from being automatically redirected UNTIL the authentication is verified.
